"""Slack Incoming Webhook reporter for autonomous investigation reports.

Sends Block Kit formatted investigation reports to Slack after each gate evaluation.
Demonstrates autonomous report delivery for Airbyte+Slack integration judges.
"""
from __future__ import annotations

import os

import httpx

_PLACEHOLDER_PREFIX = "https://hooks.slack.com/services/YOUR"


async def send_investigation_report(
    episode_id: str,
    decision: str,
    composite_score: float,
    attribution: str,
) -> bool:
    """Send investigation report to Slack via Incoming Webhook.

    Returns True if the webhook POST returned 200, False otherwise.
    Silently returns False if SLACK_WEBHOOK_URL is not configured or is a placeholder.
    """
    webhook_url = os.getenv("SLACK_WEBHOOK_URL", "")
    if not webhook_url or webhook_url.startswith(_PLACEHOLDER_PREFIX):
        return False

    color = (
        "#f85149" if decision == "NO-GO"
        else "#e3b341" if decision == "ESCALATE"
        else "#3fb950"
    )
    _ = color  # reserved for future attachment color support

    payload = {
        "text": f"Sentinel Investigation Report - Episode {episode_id}",
        "blocks": [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": f"Sentinel: {decision}"},
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": (
                        f"*Episode:* `{episode_id}`\n"
                        f"*Decision:* `{decision}` (score: `{composite_score:.2f}`)\n"
                        f"*Attribution:* {attribution}"
                    ),
                },
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": (
                            "Generated by Sentinel autonomous investigation pipeline | "
                            "Airbyte -> Slack delivery"
                        ),
                    }
                ],
            },
        ],
    }
    try:
        async with httpx.AsyncClient() as client:
            r = await client.post(webhook_url, json=payload, timeout=5.0)
            return r.status_code == 200
    except Exception:
        return False
